// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudOperationsEntityFramework.Models
{
    public partial class Student
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Class { get; set; }
        public int Id { get; set; }
    }
}